version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    env_file:
      - .env.local
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "33060:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - calendar_net
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    env_file:
      - .env.local
    ports:
      - "5672:5672"   # RabbitMQ main port
      - "15672:15672" # RabbitMQ management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - calendar_net
  redis:
    image: redis:7.2
    restart: always
    env_file:
      - .env.local
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - calendar_net
  nocobase:
    image: nocobase/nocobase:latest
    restart: always
    env_file:
      - .env.local
    ports:
      - "13030:13030"
    depends_on:
      - db
      - redis
    networks:
      - calendar_net
volumes:
  db_data:
  rabbitmq_data:
  redis_data:
networks:
  calendar_net:
    driver: bridge
