version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_USER: devuser
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: calendar_todo
      MYSQL_PASSWORD: root_password
      MYSQL_ALLOW_EMPTY_PASSWORD: false
      MYSQL_RANDOM_ROOT_PASSWORD: false
      TZ: Asia/Ho_Chi_Minh
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "33060:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - calendar_net
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"   # RabbitMQ main port
      - "15672:15672" # RabbitMQ management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest_password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - calendar_net
volumes:
  db_data:
  rabbitmq_data:

networks:
  calendar_net:
    driver: bridge
