version: '3.8'

services:
  app:
    build: .
    ports:
      - "3050:3050"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mysql://root:password@mysql:3306/calendar_todo_db
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./dist:/app/dist
      - ./node_modules:/app/node_modules
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: calendar_todo_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
