version: '3.8'

services:
  app:
    build: .
    ports:
      - "3050:3050"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./dist:/app/dist
      - ./node_modules:/app/node_modules
