version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: calendar_todo
      MYSQL_USER: devuser
      MYSQL_PASSWORD: n8X@qR5z!Lm2
      TZ: Asia/Ho_Chi_Minh
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "33060:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
